# Form implementation generated from reading ui file 'D:\HK2_2025_2026\KTLT_K25411E\Event_Check_in_Management\ui\AttendeeDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AttendeeDialog(object):
    def setupUi(self, AttendeeDialog):
        AttendeeDialog.setObjectName("AttendeeDialog")
        AttendeeDialog.resize(500, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(AttendeeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=AttendeeDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.nameInput = QtWidgets.QLineEdit(parent=AttendeeDialog)
        self.nameInput.setObjectName("nameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameInput)
        self.label_2 = QtWidgets.QLabel(parent=AttendeeDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.emailInput = QtWidgets.QLineEdit(parent=AttendeeDialog)
        self.emailInput.setObjectName("emailInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.emailInput)
        self.label_3 = QtWidgets.QLabel(parent=AttendeeDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.phoneInput = QtWidgets.QLineEdit(parent=AttendeeDialog)
        self.phoneInput.setObjectName("phoneInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phoneInput)
        self.label_4 = QtWidgets.QLabel(parent=AttendeeDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.organizationInput = QtWidgets.QLineEdit(parent=AttendeeDialog)
        self.organizationInput.setObjectName("organizationInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.organizationInput)
        self.label_5 = QtWidgets.QLabel(parent=AttendeeDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.positionInput = QtWidgets.QLineEdit(parent=AttendeeDialog)
        self.positionInput.setObjectName("positionInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.positionInput)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(parent=AttendeeDialog)
        self.btnSave.setStyleSheet("padding: 8px 15px;")
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(parent=AttendeeDialog)
        self.btnCancel.setStyleSheet("padding: 8px 15px;")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AttendeeDialog)
        self.btnCancel.clicked.connect(AttendeeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AttendeeDialog)

    def retranslateUi(self, AttendeeDialog):
        _translate = QtCore.QCoreApplication.translate
        AttendeeDialog.setWindowTitle(_translate("AttendeeDialog", "Add/Edit Attendee"))
        self.label.setText(_translate("AttendeeDialog", "Full Name:"))
        self.nameInput.setPlaceholderText(_translate("AttendeeDialog", "Enter full name..."))
        self.label_2.setText(_translate("AttendeeDialog", "Email:"))
        self.emailInput.setPlaceholderText(_translate("AttendeeDialog", "Enter email..."))
        self.label_3.setText(_translate("AttendeeDialog", "Phone Number:"))
        self.phoneInput.setPlaceholderText(_translate("AttendeeDialog", "Enter phone number..."))
        self.label_4.setText(_translate("AttendeeDialog", "Organization:"))
        self.organizationInput.setPlaceholderText(_translate("AttendeeDialog", "Enter organization..."))
        self.label_5.setText(_translate("AttendeeDialog", "Position:"))
        self.positionInput.setPlaceholderText(_translate("AttendeeDialog", "Enter position..."))
        self.btnSave.setText(_translate("AttendeeDialog", "💾 Save"))
        self.btnCancel.setText(_translate("AttendeeDialog", "❌ Cancel"))
