# Form implementation generated from reading ui file 'D:\HK2_2025_2026\KTLT_K25411E\Event_Check_in_Management\ui\ChangePasswordDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChangePasswordDialog(object):
    def setupUi(self, ChangePasswordDialog):
        ChangePasswordDialog.setObjectName("ChangePasswordDialog")
        ChangePasswordDialog.resize(400, 340)
        ChangePasswordDialog.setMinimumSize(QtCore.QSize(400, 340))
        ChangePasswordDialog.setMaximumSize(QtCore.QSize(400, 340))
        self.verticalLayout = QtWidgets.QVBoxLayout(ChangePasswordDialog)
        self.verticalLayout.setContentsMargins(30, 24, 30, 24)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=ChangePasswordDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: #2c3e50; margin-bottom: 4px;")
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.lblUser = QtWidgets.QLabel(parent=ChangePasswordDialog)
        self.lblUser.setStyleSheet("color: #7f8c8d; font-size: 12px;")
        self.lblUser.setText("")
        self.lblUser.setObjectName("lblUser")
        self.verticalLayout.addWidget(self.lblUser)
        self.lblOldPwd = QtWidgets.QLabel(parent=ChangePasswordDialog)
        self.lblOldPwd.setStyleSheet("font-weight: bold; font-size: 12px;")
        self.lblOldPwd.setObjectName("lblOldPwd")
        self.verticalLayout.addWidget(self.lblOldPwd)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditOldPwd = QtWidgets.QLineEdit(parent=ChangePasswordDialog)
        self.lineEditOldPwd.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEditOldPwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditOldPwd.setObjectName("lineEditOldPwd")
        self.horizontalLayout.addWidget(self.lineEditOldPwd)
        self.btnToggleOld = QtWidgets.QPushButton(parent=ChangePasswordDialog)
        self.btnToggleOld.setMinimumSize(QtCore.QSize(36, 36))
        self.btnToggleOld.setMaximumSize(QtCore.QSize(36, 36))
        self.btnToggleOld.setStyleSheet("QPushButton { \n"
"    background:#ecf0f1; \n"
"    border-radius:6px; \n"
"    border:1px solid #bdc3c7; \n"
"    font-size:14px; \n"
"}\n"
"QPushButton:hover { \n"
"    background:#d5dbdb; \n"
"}")
        self.btnToggleOld.setObjectName("btnToggleOld")
        self.horizontalLayout.addWidget(self.btnToggleOld)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblNewPwd = QtWidgets.QLabel(parent=ChangePasswordDialog)
        self.lblNewPwd.setStyleSheet("font-weight: bold; font-size: 12px;")
        self.lblNewPwd.setObjectName("lblNewPwd")
        self.verticalLayout.addWidget(self.lblNewPwd)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditNewPwd = QtWidgets.QLineEdit(parent=ChangePasswordDialog)
        self.lineEditNewPwd.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEditNewPwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditNewPwd.setObjectName("lineEditNewPwd")
        self.horizontalLayout_2.addWidget(self.lineEditNewPwd)
        self.btnToggleNew = QtWidgets.QPushButton(parent=ChangePasswordDialog)
        self.btnToggleNew.setMinimumSize(QtCore.QSize(36, 36))
        self.btnToggleNew.setMaximumSize(QtCore.QSize(36, 36))
        self.btnToggleNew.setStyleSheet("QPushButton { \n"
"    background:#ecf0f1; \n"
"    border-radius:6px; \n"
"    border:1px solid #bdc3c7; \n"
"    font-size:14px; \n"
"}\n"
"QPushButton:hover { \n"
"    background:#d5dbdb; \n"
"}")
        self.btnToggleNew.setObjectName("btnToggleNew")
        self.horizontalLayout_2.addWidget(self.btnToggleNew)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lblConfirmPwd = QtWidgets.QLabel(parent=ChangePasswordDialog)
        self.lblConfirmPwd.setStyleSheet("font-weight: bold; font-size: 12px;")
        self.lblConfirmPwd.setObjectName("lblConfirmPwd")
        self.verticalLayout.addWidget(self.lblConfirmPwd)
        self.lineEditConfirmPwd = QtWidgets.QLineEdit(parent=ChangePasswordDialog)
        self.lineEditConfirmPwd.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEditConfirmPwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditConfirmPwd.setObjectName("lineEditConfirmPwd")
        self.verticalLayout.addWidget(self.lineEditConfirmPwd)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(parent=ChangePasswordDialog)
        self.btnSave.setMinimumSize(QtCore.QSize(0, 38))
        self.btnSave.setStyleSheet("QPushButton { \n"
"    background:#2ecc71; \n"
"    color:white; \n"
"    border-radius:6px;\n"
"    font-size:13px; \n"
"    font-weight:bold; \n"
"    padding: 0 16px; \n"
"}\n"
"QPushButton:hover { \n"
"    background:#27ae60; \n"
"}")
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_3.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(parent=ChangePasswordDialog)
        self.btnCancel.setMinimumSize(QtCore.QSize(0, 38))
        self.btnCancel.setStyleSheet("QPushButton { \n"
"    background:#ecf0f1; \n"
"    color:#7f8c8d; \n"
"    border-radius:6px;\n"
"    font-size:13px; \n"
"    padding: 0 16px; \n"
"}\n"
"QPushButton:hover { \n"
"    background:#d5dbdb; \n"
"}")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(ChangePasswordDialog)
        self.btnCancel.clicked.connect(ChangePasswordDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ChangePasswordDialog)

    def retranslateUi(self, ChangePasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        ChangePasswordDialog.setWindowTitle(_translate("ChangePasswordDialog", "Change Password"))
        self.lblTitle.setText(_translate("ChangePasswordDialog", "🔐  Change Password"))
        self.lblOldPwd.setText(_translate("ChangePasswordDialog", "Current password:"))
        self.lineEditOldPwd.setPlaceholderText(_translate("ChangePasswordDialog", "Enter current password..."))
        self.btnToggleOld.setText(_translate("ChangePasswordDialog", "👁"))
        self.lblNewPwd.setText(_translate("ChangePasswordDialog", "New password:"))
        self.lineEditNewPwd.setPlaceholderText(_translate("ChangePasswordDialog", "Minimum 6 characters..."))
        self.btnToggleNew.setText(_translate("ChangePasswordDialog", "👁"))
        self.lblConfirmPwd.setText(_translate("ChangePasswordDialog", "Confirm new password:"))
        self.lineEditConfirmPwd.setPlaceholderText(_translate("ChangePasswordDialog", "Re-enter new password..."))
        self.btnSave.setText(_translate("ChangePasswordDialog", "💾  Save Password"))
        self.btnCancel.setText(_translate("ChangePasswordDialog", "Cancel"))
