# Form implementation generated from reading ui file 'D:\GIT_TDLT\Final-Project-Programming-Techniques\ui\EventDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EventDialog(object):
    def setupUi(self, EventDialog):
        EventDialog.setObjectName("EventDialog")
        EventDialog.resize(543, 371)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\GIT_TDLT\\Final-Project-Programming-Techniques\\ui\\../images/add_edit_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        EventDialog.setWindowIcon(icon)
        EventDialog.setStyleSheet("background-color: #f1f5f9;")
        self.verticalLayout = QtWidgets.QVBoxLayout(EventDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=EventDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.nameInput = QtWidgets.QLineEdit(parent=EventDialog)
        self.nameInput.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"background-color: #f1f5f9;")
        self.nameInput.setObjectName("nameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameInput)
        self.label_2 = QtWidgets.QLabel(parent=EventDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.dateInput = QtWidgets.QDateEdit(parent=EventDialog)
        self.dateInput.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: #f1f5f9;")
        self.dateInput.setCalendarPopup(True)
        self.dateInput.setObjectName("dateInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateInput)
        self.label_3 = QtWidgets.QLabel(parent=EventDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.timeInput = QtWidgets.QTimeEdit(parent=EventDialog)
        self.timeInput.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: #f1f5f9;")
        self.timeInput.setObjectName("timeInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.timeInput)
        self.label_4 = QtWidgets.QLabel(parent=EventDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.locationInput = QtWidgets.QLineEdit(parent=EventDialog)
        self.locationInput.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: #f1f5f9;")
        self.locationInput.setObjectName("locationInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.locationInput)
        self.label_5 = QtWidgets.QLabel(parent=EventDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.descriptionInput = QtWidgets.QTextEdit(parent=EventDialog)
        self.descriptionInput.setMaximumSize(QtCore.QSize(16777215, 100))
        self.descriptionInput.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: #f1f5f9;")
        self.descriptionInput.setObjectName("descriptionInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.descriptionInput)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(parent=EventDialog)
        self.btnSave.setStyleSheet("padding: 8px 15px;\n"
"background-color: #3b82f6;\n"
"color: rgb(255, 255, 255);")
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(parent=EventDialog)
        self.btnCancel.setStyleSheet("padding: 8px 15px;\n"
"background-color: #ef4444;\n"
"color: rgb(255, 255, 255);")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(EventDialog)
        self.btnCancel.clicked.connect(EventDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EventDialog)

    def retranslateUi(self, EventDialog):
        _translate = QtCore.QCoreApplication.translate
        EventDialog.setWindowTitle(_translate("EventDialog", "Add/Edit Event"))
        self.label.setText(_translate("EventDialog", "Name"))
        self.nameInput.setPlaceholderText(_translate("EventDialog", "Enter event name..."))
        self.label_2.setText(_translate("EventDialog", "Date"))
        self.label_3.setText(_translate("EventDialog", "Time"))
        self.label_4.setText(_translate("EventDialog", "Place"))
        self.locationInput.setPlaceholderText(_translate("EventDialog", "Enter venue..."))
        self.label_5.setText(_translate("EventDialog", "Description"))
        self.descriptionInput.setPlaceholderText(_translate("EventDialog", "Enter event description..."))
        self.btnSave.setText(_translate("EventDialog", "💾 SAVE"))
        self.btnCancel.setText(_translate("EventDialog", "❌ CANCEL"))