# Form implementation generated from reading ui file 'D:\HK2_2025_2026\KTLT_K25411E\Event_Check_in_Management\ui\ForgotPasswordDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ForgotPasswordDialog(object):
    def setupUi(self, ForgotPasswordDialog):
        ForgotPasswordDialog.setObjectName("ForgotPasswordDialog")
        ForgotPasswordDialog.resize(420, 320)
        ForgotPasswordDialog.setMinimumSize(QtCore.QSize(420, 320))
        ForgotPasswordDialog.setMaximumSize(QtCore.QSize(420, 320))
        self.verticalLayout = QtWidgets.QVBoxLayout(ForgotPasswordDialog)
        self.verticalLayout.setContentsMargins(30, 24, 30, 24)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=ForgotPasswordDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: #2c3e50; margin-bottom: 4px;")
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.lblDesc = QtWidgets.QLabel(parent=ForgotPasswordDialog)
        self.lblDesc.setStyleSheet("color: #7f8c8d; font-size: 12px;")
        self.lblDesc.setWordWrap(True)
        self.lblDesc.setObjectName("lblDesc")
        self.verticalLayout.addWidget(self.lblDesc)
        self.lblUsername = QtWidgets.QLabel(parent=ForgotPasswordDialog)
        self.lblUsername.setStyleSheet("font-weight: bold; font-size: 12px;")
        self.lblUsername.setObjectName("lblUsername")
        self.verticalLayout.addWidget(self.lblUsername)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=ForgotPasswordDialog)
        self.lineEditUsername.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.horizontalLayout.addWidget(self.lineEditUsername)
        self.btnVerifyUser = QtWidgets.QPushButton(parent=ForgotPasswordDialog)
        self.btnVerifyUser.setMinimumSize(QtCore.QSize(0, 36))
        self.btnVerifyUser.setStyleSheet("QPushButton { \n"
"    background:#3498db; \n"
"    color:white; \n"
"    border-radius:6px; \n"
"    font-size:12px; \n"
"    padding: 0 12px; \n"
"}\n"
"QPushButton:hover { \n"
"    background:#2980b9; \n"
"}")
        self.btnVerifyUser.setObjectName("btnVerifyUser")
        self.horizontalLayout.addWidget(self.btnVerifyUser)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblQuestion = QtWidgets.QLabel(parent=ForgotPasswordDialog)
        self.lblQuestion.setStyleSheet("font-weight: bold; font-size: 12px;")
        self.lblQuestion.setObjectName("lblQuestion")
        self.verticalLayout.addWidget(self.lblQuestion)
        self.lblQuestionText = QtWidgets.QLabel(parent=ForgotPasswordDialog)
        self.lblQuestionText.setStyleSheet("color: #2980b9; \n"
"font-style: italic; \n"
"font-size: 12px; \n"
"padding: 6px 10px; \n"
"background:#eaf4fd; \n"
"border-radius:6px;")
        self.lblQuestionText.setText("")
        self.lblQuestionText.setWordWrap(True)
        self.lblQuestionText.setObjectName("lblQuestionText")
        self.verticalLayout.addWidget(self.lblQuestionText)
        self.lblAnswer = QtWidgets.QLabel(parent=ForgotPasswordDialog)
        self.lblAnswer.setStyleSheet("font-weight: bold; font-size: 12px;")
        self.lblAnswer.setObjectName("lblAnswer")
        self.verticalLayout.addWidget(self.lblAnswer)
        self.lineEditAnswer = QtWidgets.QLineEdit(parent=ForgotPasswordDialog)
        self.lineEditAnswer.setMinimumSize(QtCore.QSize(0, 36))
        self.lineEditAnswer.setObjectName("lineEditAnswer")
        self.verticalLayout.addWidget(self.lineEditAnswer)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnConfirm = QtWidgets.QPushButton(parent=ForgotPasswordDialog)
        self.btnConfirm.setMinimumSize(QtCore.QSize(0, 38))
        self.btnConfirm.setStyleSheet("QPushButton { \n"
"    background:#2ecc71; \n"
"    color:white; \n"
"    border-radius:6px;\n"
"    font-size:13px; \n"
"    font-weight:bold; \n"
"    padding: 0 16px; \n"
"}\n"
"QPushButton:hover { \n"
"    background:#27ae60; \n"
"}")
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout_2.addWidget(self.btnConfirm)
        self.btnCancel = QtWidgets.QPushButton(parent=ForgotPasswordDialog)
        self.btnCancel.setMinimumSize(QtCore.QSize(0, 38))
        self.btnCancel.setStyleSheet("QPushButton { \n"
"    background:#ecf0f1; \n"
"    color:#7f8c8d; \n"
"    border-radius:6px;\n"
"    font-size:13px; \n"
"    padding: 0 16px; \n"
"}\n"
"QPushButton:hover { \n"
"    background:#d5dbdb; \n"
"}")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ForgotPasswordDialog)
        self.btnCancel.clicked.connect(ForgotPasswordDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ForgotPasswordDialog)

    def retranslateUi(self, ForgotPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        ForgotPasswordDialog.setWindowTitle(_translate("ForgotPasswordDialog", "Forgot Password"))
        self.lblTitle.setText(_translate("ForgotPasswordDialog", "🔓  Forgot Password"))
        self.lblDesc.setText(_translate("ForgotPasswordDialog", "Enter your username and answer the security question."))
        self.lblUsername.setText(_translate("ForgotPasswordDialog", "Username:"))
        self.lineEditUsername.setPlaceholderText(_translate("ForgotPasswordDialog", "Enter username..."))
        self.btnVerifyUser.setText(_translate("ForgotPasswordDialog", "Verify"))
        self.lblQuestion.setText(_translate("ForgotPasswordDialog", "Security question:"))
        self.lblAnswer.setText(_translate("ForgotPasswordDialog", "Answer:"))
        self.lineEditAnswer.setPlaceholderText(_translate("ForgotPasswordDialog", "Enter your answer..."))
        self.btnConfirm.setText(_translate("ForgotPasswordDialog", "✔  Reset Password"))
        self.btnCancel.setText(_translate("ForgotPasswordDialog", "Cancel"))
