from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(460, 540)
        LoginWindow.setMinimumSize(QtCore.QSize(460, 540))
        LoginWindow.setMaximumSize(QtCore.QSize(460, 540))
        LoginWindow.setStyleSheet("background-color: #f0f7ff;")

        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(40, 28, 40, 28)
        self.verticalLayout.setSpacing(0)

        self.lblLogo = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont(); font.setPointSize(48)
        self.lblLogo.setFont(font)
        self.lblLogo.setStyleSheet("background: transparent;")
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayout.addWidget(self.lblLogo)

        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        font2 = QtGui.QFont(); font2.setFamily("Palatino Linotype"); font2.setPointSize(18); font2.setBold(True)
        self.lblTitle.setFont(font2)
        self.lblTitle.setStyleSheet("color: #1e293b; background: transparent;")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)

        self.lblSubtitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblSubtitle.setStyleSheet("color: #64748b; font-size: 12px; margin-bottom: 16px; background: transparent;")
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout.addWidget(self.lblSubtitle)

        self.cardWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.cardWidget.setStyleSheet("QWidget#cardWidget { background-color: white; border-radius: 14px; border: 1px solid #e2e8f0; }")
        self.cardWidget.setObjectName("cardWidget")
        self.cardLayout = QtWidgets.QVBoxLayout(self.cardWidget)
        self.cardLayout.setContentsMargins(28, 24, 28, 24)
        self.cardLayout.setSpacing(10)

        self.lblUsername = QtWidgets.QLabel(parent=self.cardWidget)
        self.lblUsername.setStyleSheet("font-weight: bold; color: #374151; font-size: 13px; background: transparent;")
        self.lblUsername.setObjectName("lblUsername")
        self.cardLayout.addWidget(self.lblUsername)

        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.cardWidget)
        font3 = QtGui.QFont(); font3.setPointSize(12)
        self.lineEditUsername.setFont(font3)
        self.lineEditUsername.setMinimumHeight(38)
        self.lineEditUsername.setStyleSheet("QLineEdit { color: #111827; background: white; border: 1px solid #d1d5db; border-radius: 6px; padding: 6px 10px; } QLineEdit:focus { border: 1px solid #3b82f6; }")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.cardLayout.addWidget(self.lineEditUsername)

        self.lblPassword = QtWidgets.QLabel(parent=self.cardWidget)
        self.lblPassword.setStyleSheet("font-weight: bold; color: #374151; font-size: 13px; background: transparent;")
        self.lblPassword.setObjectName("lblPassword")
        self.cardLayout.addWidget(self.lblPassword)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.cardWidget)
        self.lineEditPassword.setMinimumHeight(38)
        self.lineEditPassword.setStyleSheet("QLineEdit { color: #111827; background: white; border: 1px solid #d1d5db; border-radius: 6px; padding: 6px 10px; font-size: 12pt; } QLineEdit:focus { border: 1px solid #3b82f6; }")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayout.addWidget(self.lineEditPassword)

        self.btnTogglePwd = QtWidgets.QPushButton(parent=self.cardWidget)
        self.btnTogglePwd.setMaximumSize(QtCore.QSize(40, 40))
        self.btnTogglePwd.setMinimumSize(QtCore.QSize(40, 38))
        self.btnTogglePwd.setStyleSheet("QPushButton { background: #f1f5f9; border-radius: 6px; border: 1px solid #e2e8f0; font-size: 16px; } QPushButton:hover { background: #e2e8f0; }")
        self.btnTogglePwd.setObjectName("btnTogglePwd")
        self.horizontalLayout.addWidget(self.btnTogglePwd)
        self.cardLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.checkBoxRemember = QtWidgets.QCheckBox(parent=self.cardWidget)
        font4 = QtGui.QFont(); font4.setPointSize(10)
        self.checkBoxRemember.setFont(font4)
        self.checkBoxRemember.setStyleSheet("color: #374151; background: transparent;")
        self.checkBoxRemember.setCheckable(True)
        self.checkBoxRemember.setTristate(False)
        self.checkBoxRemember.setObjectName("checkBoxRemember")
        self.horizontalLayout_2.addWidget(self.checkBoxRemember)

        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)

        self.btnForgotPassword = QtWidgets.QPushButton(parent=self.cardWidget)
        self.btnForgotPassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnForgotPassword.setStyleSheet("QPushButton { color: #3b82f6; font-size: 12px; border: none; background: transparent; } QPushButton:hover { color: #2563eb; text-decoration: underline; }")
        self.btnForgotPassword.setFlat(True)
        self.btnForgotPassword.setObjectName("btnForgotPassword")
        self.horizontalLayout_2.addWidget(self.btnForgotPassword)
        self.cardLayout.addLayout(self.horizontalLayout_2)

        self.line = QtWidgets.QFrame(parent=self.cardWidget)
        self.line.setStyleSheet("color: #e2e8f0;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.cardLayout.addWidget(self.line)

        self.btnLogin = QtWidgets.QPushButton(parent=self.cardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.btnLogin.setSizePolicy(sizePolicy)
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 42))
        font5 = QtGui.QFont(); font5.setBold(True); font5.setPointSize(13)
        self.btnLogin.setFont(font5)
        self.btnLogin.setStyleSheet("QPushButton { background-color: #3b82f6; color: white; font-size: 14px; font-weight: bold; border-radius: 8px; border: none; } QPushButton:hover { background-color: #2563eb; } QPushButton:pressed { background-color: #1d4ed8; }")
        self.btnLogin.setObjectName("btnLogin")
        self.cardLayout.addWidget(self.btnLogin)

        self.btnExit = QtWidgets.QPushButton(parent=self.cardWidget)
        self.btnExit.setMinimumSize(QtCore.QSize(0, 36))
        self.btnExit.setStyleSheet("QPushButton { background: #f1f5f9; color: #374151; font-size: 13px; border-radius: 8px; border: 1px solid #e2e8f0; } QPushButton:hover { background: #fee2e2; color: #ef4444; border-color: #fca5a5; }")
        self.btnExit.setObjectName("btnExit")
        self.cardLayout.addWidget(self.btnExit)

        self.verticalLayout.addWidget(self.cardWidget)

        self.lblVersion = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblVersion.setStyleSheet("color: #94a3b8; font-size: 10px; margin-top: 12px; background: transparent;")
        self.lblVersion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblVersion.setObjectName("lblVersion")
        self.verticalLayout.addWidget(self.lblVersion)

        LoginWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login — Event Check-in Management System"))
        self.lblLogo.setText(_translate("LoginWindow", "🎫"))
        self.lblTitle.setText(_translate("LoginWindow", "Event Check-in Management"))
        self.lblSubtitle.setText(_translate("LoginWindow", "Sign in to continue"))
        self.lblUsername.setText(_translate("LoginWindow", "Username"))
        self.lblPassword.setText(_translate("LoginWindow", "Password"))
        self.btnTogglePwd.setText(_translate("LoginWindow", "👁"))
        self.checkBoxRemember.setText(_translate("LoginWindow", "Remember username"))
        self.btnForgotPassword.setText(_translate("LoginWindow", "Forgot password?"))
        self.btnLogin.setText(_translate("LoginWindow", "🔑  Sign In"))
        self.btnExit.setText(_translate("LoginWindow", "❌  Exit"))
        self.lblVersion.setText(_translate("LoginWindow", "v1.0.0 — Event Management System © 2026"))