# Form implementation generated from reading ui file 'D:\GIT_TDLT\Final-Project-Programming-Techniques\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(960, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerBar = QtWidgets.QWidget(parent=self.centralwidget)
        self.headerBar.setMinimumSize(QtCore.QSize(0, 54))
        self.headerBar.setMaximumSize(QtCore.QSize(16777215, 54))
        self.headerBar.setStyleSheet("QWidget#headerBar {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,\n"
"        stop:0 #1e293b, stop:1 #334155);\n"
"}")
        self.headerBar.setObjectName("headerBar")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout(self.headerBar)
        self.horizontalLayout_header.setContentsMargins(16, 0, 16, 0)
        self.horizontalLayout_header.setSpacing(10)
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        self.titleLabel = QtWidgets.QLabel(parent=self.headerBar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: white; letter-spacing: 1px;")
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_header.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem)
        self.lblRoleBadge = QtWidgets.QLabel(parent=self.headerBar)
        self.lblRoleBadge.setMinimumSize(QtCore.QSize(0, 26))
        self.lblRoleBadge.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lblRoleBadge.setStyleSheet("QLabel { \n"
"    background:#3b82f6; \n"
"    color:white; \n"
"    border-radius:5px;\n"
"    font-size:11px; \n"
"    font-weight:bold; \n"
"    padding: 0 8px; \n"
"}")
        self.lblRoleBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblRoleBadge.setObjectName("lblRoleBadge")
        self.horizontalLayout_header.addWidget(self.lblRoleBadge)
        self.lblLoginUser = QtWidgets.QLabel(parent=self.headerBar)
        self.lblLoginUser.setStyleSheet("color: #ecf0f1; font-size: 12px;")
        self.lblLoginUser.setObjectName("lblLoginUser")
        self.horizontalLayout_header.addWidget(self.lblLoginUser)
        self.btnChangePassword = QtWidgets.QPushButton(parent=self.headerBar)
        self.btnChangePassword.setMinimumSize(QtCore.QSize(0, 30))
        self.btnChangePassword.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnChangePassword.setStyleSheet("QPushButton { \n"
"    background:#2563eb; \n"
"    color:white; \n"
"    border-radius:6px;\n"
"    font-size:12px; \n"
"    padding: 0 12px; \n"
"    border:none; \n"
"}\n"
"QPushButton:hover { \n"
"    background:#2563eb; \n"
"}")
        self.btnChangePassword.setObjectName("btnChangePassword")
        self.horizontalLayout_header.addWidget(self.btnChangePassword)
        self.btnLogout = QtWidgets.QPushButton(parent=self.headerBar)
        self.btnLogout.setMinimumSize(QtCore.QSize(0, 30))
        self.btnLogout.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnLogout.setStyleSheet("QPushButton { \n"
"    background:#ef4444; \n"
"    color:white; \n"
"    border-radius:6px;\n"
"    font-size:12px; \n"
"    padding: 0 12px; \n"
"    border:none; \n"
"}\n"
"QPushButton:hover { \n"
"    background:#dc2626; \n"
"}")
        self.btnLogout.setObjectName("btnLogout")
        self.horizontalLayout_header.addWidget(self.btnLogout)
        self.verticalLayout.addWidget(self.headerBar)
        self.contentWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.contentWidget.setStyleSheet("background-color: #f8fafc;")
        self.contentWidget.setObjectName("contentWidget")
        self.contentLayout = QtWidgets.QVBoxLayout(self.contentWidget)
        self.contentLayout.setContentsMargins(12, 10, 12, 10)
        self.contentLayout.setSpacing(6)
        self.contentLayout.setObjectName("contentLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.contentWidget)
        self.tabWidget.setStyleSheet(
            "QTabBar::tab { border: 1px solid #767676; color: black; min-width: 130px; }"
        )
        self.tabWidget.setObjectName("tabWidget")
        self.eventTab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.eventTab.setFont(font)
        self.eventTab.setStyleSheet("")
        self.eventTab.setObjectName("eventTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.eventTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # Search bar cho Event (vấn đề 10)
        self.horizontalLayout_event_search = QtWidgets.QHBoxLayout()
        self.horizontalLayout_event_search.setObjectName("horizontalLayout_event_search")
        self.labelEventSearch = QtWidgets.QLabel(parent=self.eventTab)
        self.labelEventSearch.setStyleSheet("color: rgb(0, 0, 0);")
        self.labelEventSearch.setObjectName("labelEventSearch")
        self.horizontalLayout_event_search.addWidget(self.labelEventSearch)
        self.eventSearch = QtWidgets.QLineEdit(parent=self.eventTab)
        self.eventSearch.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #919191;\n"
"    border-color:#707070;\n"
"    padding: 2px;\n"
"    color:black;\n"
"}")
        self.eventSearch.setObjectName("eventSearch")
        self.horizontalLayout_event_search.addWidget(self.eventSearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout_event_search)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddEvent = QtWidgets.QPushButton(parent=self.eventTab)
        self.btnAddEvent.setStyleSheet("padding: 10px; font-size: 13px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: #3b82f6;")
        self.btnAddEvent.setObjectName("btnAddEvent")
        self.horizontalLayout.addWidget(self.btnAddEvent)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.eventTable = QtWidgets.QTableWidget(parent=self.eventTab)
        self.eventTable.setStyleSheet("background-color: white;")
        self.eventTable.setObjectName("eventTable")
        self.eventTable.setColumnCount(6)
        self.eventTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.eventTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.eventTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.eventTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.eventTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.eventTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.eventTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.eventTable)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnViewEvent = QtWidgets.QPushButton(parent=self.eventTab)
        self.btnViewEvent.setStyleSheet("background-color: #2563eb;\n"
"color: rgb(255, 255, 255);")
        self.btnViewEvent.setObjectName("btnViewEvent")
        self.horizontalLayout_2.addWidget(self.btnViewEvent)
        self.btnEditEvent = QtWidgets.QPushButton(parent=self.eventTab)
        self.btnEditEvent.setStyleSheet("color :rgb(255, 255, 255);\n"
"background-color: #2563eb;")
        self.btnEditEvent.setObjectName("btnEditEvent")
        self.horizontalLayout_2.addWidget(self.btnEditEvent)
        self.btnDeleteEvent = QtWidgets.QPushButton(parent=self.eventTab)
        self.btnDeleteEvent.setStyleSheet("background-color: #ef4444; color: white;")
        self.btnDeleteEvent.setObjectName("btnDeleteEvent")
        self.horizontalLayout_2.addWidget(self.btnDeleteEvent)
        self.btnRefreshEvent = QtWidgets.QPushButton(parent=self.eventTab)
        self.btnRefreshEvent.setStyleSheet("background-color: #94a3b8; color: white;")
        self.btnRefreshEvent.setObjectName("btnRefreshEvent")
        self.horizontalLayout_2.addWidget(self.btnRefreshEvent)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_event_page = QtWidgets.QHBoxLayout()
        self.horizontalLayout_event_page.setObjectName("horizontalLayout_event_page")
        self.btnExportEvent = QtWidgets.QPushButton(parent=self.eventTab)
        self.btnExportEvent.setStyleSheet("background-color: #94a3b8; color: white; padding: 6px 12px;")
        self.btnExportEvent.setObjectName("btnExportEvent")
        self.horizontalLayout_event_page.addWidget(self.btnExportEvent)
        spacerPage_event = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_event_page.addItem(spacerPage_event)
        self.btnPrevEvent = QtWidgets.QPushButton(parent=self.eventTab)
        self.btnPrevEvent.setStyleSheet("background-color: #2563eb; color: white; padding: 6px 10px;")
        self.btnPrevEvent.setObjectName("btnPrevEvent")
        self.horizontalLayout_event_page.addWidget(self.btnPrevEvent)
        self.lblPageEvent = QtWidgets.QLabel(parent=self.eventTab)
        self.lblPageEvent.setStyleSheet("color: #1e293b; font-size: 12px; padding: 0 8px;")
        self.lblPageEvent.setText("Page 1 / 1")
        self.lblPageEvent.setObjectName("lblPageEvent")
        self.horizontalLayout_event_page.addWidget(self.lblPageEvent)
        self.btnNextEvent = QtWidgets.QPushButton(parent=self.eventTab)
        self.btnNextEvent.setStyleSheet("background-color: #2563eb; color: white; padding: 6px 10px;")
        self.btnNextEvent.setObjectName("btnNextEvent")
        self.horizontalLayout_event_page.addWidget(self.btnNextEvent)
        self.verticalLayout_2.addLayout(self.horizontalLayout_event_page)
        # ── Dashboard Tab ──────────────────────────────────────
        self.dashboardTab = QtWidgets.QWidget()
        self.dashboardTab.setObjectName("dashboardTab")
        self.dashLayout = QtWidgets.QVBoxLayout(self.dashboardTab)
        self.dashLayout.setContentsMargins(20, 20, 20, 20)
        self.dashLayout.setSpacing(16)

        # Row 1: 4 stat cards
        self.dashRow1 = QtWidgets.QHBoxLayout()
        self.dashRow1.setSpacing(14)

        def make_card(obj_name, bg, label_text):
            card = QtWidgets.QWidget()
            card.setObjectName(obj_name)
            card.setStyleSheet(f"QWidget#{obj_name}{{background:{bg};border-radius:10px;padding:8px;}}")
            card.setMinimumHeight(100)
            cl = QtWidgets.QVBoxLayout(card)
            cl.setContentsMargins(16, 12, 16, 12)
            num_lbl = QtWidgets.QLabel("0")
            num_lbl.setObjectName(f"{obj_name}Num")
            num_lbl.setStyleSheet("color:white;font-size:32px;font-weight:bold;background:transparent;")
            num_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            cl.addWidget(num_lbl)
            txt_lbl = QtWidgets.QLabel(label_text)
            txt_lbl.setStyleSheet("color:rgba(255,255,255,0.85);font-size:12px;background:transparent;")
            txt_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            cl.addWidget(txt_lbl)
            return card

        self.cardTotalEvents    = make_card("cardTotalEvents",    "#3b82f6", "Total Events")
        self.cardTotalAttendees = make_card("cardTotalAttendees", "#8b5cf6", "Total Attendees")
        self.cardTotalRegs      = make_card("cardTotalRegs",      "#f59e0b", "Total Registrations")
        self.cardTotalCheckin   = make_card("cardTotalCheckin",   "#10b981", "Checked-in Today")

        self.dashRow1.addWidget(self.cardTotalEvents)
        self.dashRow1.addWidget(self.cardTotalAttendees)
        self.dashRow1.addWidget(self.cardTotalRegs)
        self.dashRow1.addWidget(self.cardTotalCheckin)
        self.dashLayout.addLayout(self.dashRow1)

        # Row 2: Upcoming events + Recent checkins
        self.dashRow2 = QtWidgets.QHBoxLayout()
        self.dashRow2.setSpacing(14)

        # Upcoming events
        self.dashUpcomingGroup = QtWidgets.QGroupBox("📅 Upcoming Events")
        self.dashUpcomingGroup.setStyleSheet("QGroupBox{font-weight:bold;font-size:13px;color:#1e293b;border:1px solid #e2e8f0;border-radius:8px;margin-top:8px;background:white;} QGroupBox::title{subcontrol-origin:margin;padding:0 8px;background:#f1f5f9;border-radius:4px;}")
        ugLayout = QtWidgets.QVBoxLayout(self.dashUpcomingGroup)
        self.dashUpcomingTable = QtWidgets.QTableWidget(0, 3)
        self.dashUpcomingTable.setObjectName("dashUpcomingTable")
        self.dashUpcomingTable.setHorizontalHeaderLabels(["Event Name", "Date", "Registered"])
        self.dashUpcomingTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.dashUpcomingTable.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers)
        self.dashUpcomingTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.dashUpcomingTable.setAlternatingRowColors(True)
        self.dashUpcomingTable.setStyleSheet("background:white;alternate-background-color:#f8fafc;gridline-color:#e2e8f0;")
        self.dashUpcomingTable.horizontalHeader().setStyleSheet("QHeaderView::section{background:#f1f5f9;color:#374151;font-weight:bold;padding:6px;border-bottom:2px solid #e2e8f0;}")
        ugLayout.addWidget(self.dashUpcomingTable)
        self.dashRow2.addWidget(self.dashUpcomingGroup, 3)

        # Recent check-ins
        self.dashRecentGroup = QtWidgets.QGroupBox("✅ Recent Check-ins")
        self.dashRecentGroup.setStyleSheet("QGroupBox{font-weight:bold;font-size:13px;color:#1e293b;border:1px solid #e2e8f0;border-radius:8px;margin-top:8px;background:white;} QGroupBox::title{subcontrol-origin:margin;padding:0 8px;background:#f1f5f9;border-radius:4px;}")
        rcLayout = QtWidgets.QVBoxLayout(self.dashRecentGroup)
        self.dashRecentTable = QtWidgets.QTableWidget(0, 3)
        self.dashRecentTable.setObjectName("dashRecentTable")
        self.dashRecentTable.setHorizontalHeaderLabels(["Name", "Event", "Time"])
        self.dashRecentTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.dashRecentTable.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers)
        self.dashRecentTable.setAlternatingRowColors(True)
        self.dashRecentTable.setStyleSheet("background:white;alternate-background-color:#f8fafc;gridline-color:#e2e8f0;")
        self.dashRecentTable.horizontalHeader().setStyleSheet("QHeaderView::section{background:#f1f5f9;color:#374151;font-weight:bold;padding:6px;border-bottom:2px solid #e2e8f0;}")
        rcLayout.addWidget(self.dashRecentTable)
        self.dashRow2.addWidget(self.dashRecentGroup, 2)

        self.dashLayout.addLayout(self.dashRow2)

        # Refresh button
        self.btnRefreshDash = QtWidgets.QPushButton("🔄 Refresh Dashboard")
        self.btnRefreshDash.setObjectName("btnRefreshDash")
        self.btnRefreshDash.setStyleSheet("background:#94a3b8;color:white;padding:7px 18px;border-radius:5px;font-size:12px;max-width:180px;")
        self.dashLayout.addWidget(self.btnRefreshDash, alignment=QtCore.Qt.AlignmentFlag.AlignRight)

        self.tabWidget.addTab(self.dashboardTab, "")
        # ── End Dashboard Tab ──────────────────────────────────
        self.tabWidget.addTab(self.eventTab, "")
        self.attendeeTab = QtWidgets.QWidget()
        self.attendeeTab.setObjectName("attendeeTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.attendeeTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.attendeeTab)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.attendeeSearch = QtWidgets.QLineEdit(parent=self.attendeeTab)
        self.attendeeSearch.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #919191; /* Độ dày, Kiểu, Màu */\n"
"       /* (Tùy chọn) Bo góc */\n"
"    border-color:#707070;\n"
"    padding: 2px;   \n"
"    color:black;          /* (Tùy chọn) Khoảng cách chữ */\n"
"}")
        self.attendeeSearch.setObjectName("attendeeSearch")
        self.horizontalLayout_3.addWidget(self.attendeeSearch)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnAddAttendee = QtWidgets.QPushButton(parent=self.attendeeTab)
        self.btnAddAttendee.setStyleSheet("padding: 10px; font-size: 13px;\n"
"background-color: #3b82f6;\n"
"color: rgb(255, 255, 255);")
        self.btnAddAttendee.setObjectName("btnAddAttendee")
        self.horizontalLayout_4.addWidget(self.btnAddAttendee)
        self.btnImportAttendee = QtWidgets.QPushButton(parent=self.attendeeTab)
        self.btnImportAttendee.setStyleSheet("background-color: #6366f1; color: white; padding: 10px; font-size: 13px; border-radius: 5px;")
        self.btnImportAttendee.setObjectName("btnImportAttendee")
        self.horizontalLayout_4.addWidget(self.btnImportAttendee)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.attendeeTable = QtWidgets.QTableWidget(parent=self.attendeeTab)
        self.attendeeTable.setStyleSheet("background-color: white;")
        self.attendeeTable.setObjectName("attendeeTable")
        self.attendeeTable.setColumnCount(6)
        self.attendeeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.attendeeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.attendeeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.attendeeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.attendeeTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.attendeeTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.attendeeTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.attendeeTable)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnEditAttendee = QtWidgets.QPushButton(parent=self.attendeeTab)
        self.btnEditAttendee.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #2563eb;")
        self.btnEditAttendee.setObjectName("btnEditAttendee")
        self.horizontalLayout_5.addWidget(self.btnEditAttendee)
        self.btnDeleteAttendee = QtWidgets.QPushButton(parent=self.attendeeTab)
        self.btnDeleteAttendee.setStyleSheet("background-color: #ef4444; color: white;")
        self.btnDeleteAttendee.setObjectName("btnDeleteAttendee")
        self.horizontalLayout_5.addWidget(self.btnDeleteAttendee)
        self.btnHistoryAttendee = QtWidgets.QPushButton(parent=self.attendeeTab)
        self.btnHistoryAttendee.setStyleSheet("background-color: #6366f1; color: white; padding: 8px 15px; border-radius: 5px;")
        self.btnHistoryAttendee.setObjectName("btnHistoryAttendee")
        self.horizontalLayout_5.addWidget(self.btnHistoryAttendee)
        self.btnRefreshAttendee = QtWidgets.QPushButton(parent=self.attendeeTab)
        self.btnRefreshAttendee.setStyleSheet("background-color: #94a3b8; color: white;")
        self.btnRefreshAttendee.setObjectName("btnRefreshAttendee")
        self.horizontalLayout_5.addWidget(self.btnRefreshAttendee)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_attendee_page = QtWidgets.QHBoxLayout()
        self.horizontalLayout_attendee_page.setObjectName("horizontalLayout_attendee_page")
        self.btnExportAttendee = QtWidgets.QPushButton(parent=self.attendeeTab)
        self.btnExportAttendee.setStyleSheet("background-color: #94a3b8; color: white; padding: 6px 12px;")
        self.btnExportAttendee.setObjectName("btnExportAttendee")
        self.horizontalLayout_attendee_page.addWidget(self.btnExportAttendee)
        spacerPage_attendee = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_attendee_page.addItem(spacerPage_attendee)
        self.btnPrevAttendee = QtWidgets.QPushButton(parent=self.attendeeTab)
        self.btnPrevAttendee.setStyleSheet("background-color: #2563eb; color: white; padding: 6px 10px;")
        self.btnPrevAttendee.setObjectName("btnPrevAttendee")
        self.horizontalLayout_attendee_page.addWidget(self.btnPrevAttendee)
        self.lblPageAttendee = QtWidgets.QLabel(parent=self.attendeeTab)
        self.lblPageAttendee.setStyleSheet("color: #1e293b; font-size: 12px; padding: 0 8px;")
        self.lblPageAttendee.setText("Page 1 / 1")
        self.lblPageAttendee.setObjectName("lblPageAttendee")
        self.horizontalLayout_attendee_page.addWidget(self.lblPageAttendee)
        self.btnNextAttendee = QtWidgets.QPushButton(parent=self.attendeeTab)
        self.btnNextAttendee.setStyleSheet("background-color: #2563eb; color: white; padding: 6px 10px;")
        self.btnNextAttendee.setObjectName("btnNextAttendee")
        self.horizontalLayout_attendee_page.addWidget(self.btnNextAttendee)
        self.verticalLayout_3.addLayout(self.horizontalLayout_attendee_page)
        self.tabWidget.addTab(self.attendeeTab, "")
        self.registrationTab = QtWidgets.QWidget()
        self.registrationTab.setObjectName("registrationTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.registrationTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=self.registrationTab)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.eventCombo = QtWidgets.QComboBox(parent=self.registrationTab)
        self.eventCombo.setStyleSheet("QComboBox{\n"
"    border: 1px solid #6f6f6f; /* Độ dày, Kiểu, Màu */\n"
"       /* (Tùy chọn) Bo góc */\n"
"    padding: 2px;    \n"
"    color: black;         /* (Tùy chọn) Khoảng cách chữ */\n"
"}")
        self.eventCombo.setObjectName("eventCombo")
        self.horizontalLayout_6.addWidget(self.eventCombo)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnRegisterAttendee = QtWidgets.QPushButton(parent=self.registrationTab)
        self.btnRegisterAttendee.setStyleSheet("padding: 10px; font-size: 13px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: #3b82f6;")
        self.btnRegisterAttendee.setObjectName("btnRegisterAttendee")
        self.horizontalLayout_7.addWidget(self.btnRegisterAttendee)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        # Search bar Registration
        self.horizontalLayout_reg_search = QtWidgets.QHBoxLayout()
        self.lblRegSearch = QtWidgets.QLabel(parent=self.registrationTab)
        self.lblRegSearch.setText("🔍 Search:")
        self.lblRegSearch.setStyleSheet("color: #374151; font-size: 13px;")
        self.horizontalLayout_reg_search.addWidget(self.lblRegSearch)
        self.registrationSearch = QtWidgets.QLineEdit(parent=self.registrationTab)
        self.registrationSearch.setPlaceholderText("Enter name, email or status (Registered / Checked-in)...")
        self.registrationSearch.setStyleSheet("padding: 6px; border: 1px solid #d1d5db; border-radius: 5px;")
        self.horizontalLayout_reg_search.addWidget(self.registrationSearch)
        self.verticalLayout_4.addLayout(self.horizontalLayout_reg_search)
        self.registrationTable = QtWidgets.QTableWidget(parent=self.registrationTab)
        self.registrationTable.setStyleSheet("background-color: white;")
        self.registrationTable.setObjectName("registrationTable")
        self.registrationTable.setColumnCount(6)
        self.registrationTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.registrationTable)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnGenerateQR = QtWidgets.QPushButton(parent=self.registrationTab)
        self.btnGenerateQR.setStyleSheet("background-color: #2563eb;\n"
"color: rgb(255, 255, 255);")
        self.btnGenerateQR.setObjectName("btnGenerateQR")
        self.horizontalLayout_8.addWidget(self.btnGenerateQR)
        self.btnCancelRegistration = QtWidgets.QPushButton(parent=self.registrationTab)
        self.btnCancelRegistration.setStyleSheet("background-color: #ef4444; color: white;")
        self.btnCancelRegistration.setObjectName("btnCancelRegistration")
        self.horizontalLayout_8.addWidget(self.btnCancelRegistration)
        self.btnRefreshRegistration = QtWidgets.QPushButton(parent=self.registrationTab)
        self.btnRefreshRegistration.setStyleSheet("background-color: #94a3b8; color: white;")
        self.btnRefreshRegistration.setObjectName("btnRefreshRegistration")
        self.horizontalLayout_8.addWidget(self.btnRefreshRegistration)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_registration_page = QtWidgets.QHBoxLayout()
        self.horizontalLayout_registration_page.setObjectName("horizontalLayout_registration_page")
        self.btnExportRegistration = QtWidgets.QPushButton(parent=self.registrationTab)
        self.btnExportRegistration.setStyleSheet("background-color: #94a3b8; color: white; padding: 6px 12px;")
        self.btnExportRegistration.setObjectName("btnExportRegistration")
        self.horizontalLayout_registration_page.addWidget(self.btnExportRegistration)
        spacerPage_registration = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_registration_page.addItem(spacerPage_registration)
        self.btnPrevRegistration = QtWidgets.QPushButton(parent=self.registrationTab)
        self.btnPrevRegistration.setStyleSheet("background-color: #2563eb; color: white; padding: 6px 10px;")
        self.btnPrevRegistration.setObjectName("btnPrevRegistration")
        self.horizontalLayout_registration_page.addWidget(self.btnPrevRegistration)
        self.lblPageRegistration = QtWidgets.QLabel(parent=self.registrationTab)
        self.lblPageRegistration.setStyleSheet("color: #1e293b; font-size: 12px; padding: 0 8px;")
        self.lblPageRegistration.setText("Page 1 / 1")
        self.lblPageRegistration.setObjectName("lblPageRegistration")
        self.horizontalLayout_registration_page.addWidget(self.lblPageRegistration)
        self.btnNextRegistration = QtWidgets.QPushButton(parent=self.registrationTab)
        self.btnNextRegistration.setStyleSheet("background-color: #2563eb; color: white; padding: 6px 10px;")
        self.btnNextRegistration.setObjectName("btnNextRegistration")
        self.horizontalLayout_registration_page.addWidget(self.btnNextRegistration)
        self.verticalLayout_4.addLayout(self.horizontalLayout_registration_page)
        self.tabWidget.addTab(self.registrationTab, "")
        self.checkinTab = QtWidgets.QWidget()
        self.checkinTab.setObjectName("checkinTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.checkinTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(parent=self.checkinTab)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.checkinEventCombo = QtWidgets.QComboBox(parent=self.checkinTab)
        self.checkinEventCombo.setStyleSheet("QComboBox{\n"
"    border: 1px solid #6f6f6f; /* Độ dày, Kiểu, Màu */\n"
"       /* (Tùy chọn) Bo góc */\n"
"    padding: 2px;     \n"
"    color: black;        /* (Tùy chọn) Khoảng cách chữ */\n"
"}")
        self.checkinEventCombo.setObjectName("checkinEventCombo")
        self.horizontalLayout_9.addWidget(self.checkinEventCombo)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.statsGroup = QtWidgets.QGroupBox(parent=self.checkinTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.statsGroup.setFont(font)
        self.statsGroup.setAutoFillBackground(False)
        self.statsGroup.setStyleSheet("QGroupBox::title {\n"
"    background-color:#f1f5f9; /* Màu nền của chữ */\n"
"    color: black;               /* Màu chữ */\n"
"    subcontrol-position: top left; /* Vị trí */\n"
"    padding: 2px;             /* Khoảng cách padding */\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid #6f6f6f; /* Độ dày, Kiểu, Màu */\n"
"       /* (Tùy chọn) Bo góc */\n"
"               \n"
"}")
        self.statsGroup.setFlat(False)
        self.statsGroup.setCheckable(False)
        self.statsGroup.setObjectName("statsGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.statsGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.statsGroup)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.totalRegisteredLabel = QtWidgets.QLabel(parent=self.statsGroup)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.totalRegisteredLabel.setFont(font)
        self.totalRegisteredLabel.setStyleSheet("color: #2563eb;")
        self.totalRegisteredLabel.setObjectName("totalRegisteredLabel")
        self.gridLayout.addWidget(self.totalRegisteredLabel, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.statsGroup)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.totalCheckedinLabel = QtWidgets.QLabel(parent=self.statsGroup)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.totalCheckedinLabel.setFont(font)
        self.totalCheckedinLabel.setStyleSheet("color: #3b82f6;")
        self.totalCheckedinLabel.setObjectName("totalCheckedinLabel")
        self.gridLayout.addWidget(self.totalCheckedinLabel, 0, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.statsGroup)
        self.checkinGroup = QtWidgets.QGroupBox(parent=self.checkinTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.checkinGroup.setFont(font)
        self.checkinGroup.setAutoFillBackground(False)
        self.checkinGroup.setStyleSheet("QGroupBox::title {\n"
"    background-color:#f1f5f9; /* Màu nền của chữ */\n"
"    color: black;               /* Màu chữ */\n"
"    subcontrol-position: top left; /* Vị trí */\n"
"    padding: 2px;             /* Khoảng cách padding */\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid #6f6f6f; /* Độ dày, Kiểu, Màu */\n"
"       /* (Tùy chọn) Bo góc */\n"
"               \n"
"}")
        self.checkinGroup.setObjectName("checkinGroup")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.checkinGroup)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(parent=self.checkinGroup)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.checkinCode = QtWidgets.QLineEdit(parent=self.checkinGroup)
        self.checkinCode.setStyleSheet("QLineEdit{\n"
"    border: 1px solid #6f6f6f; /* Độ dày, Kiểu, Màu */\n"
"       /* (Tùy chọn) Bo góc */\n"
"    padding: 2px;    \n"
"    color: black;         /* (Tùy chọn) Khoảng cách chữ */\n"
"}")
        self.checkinCode.setObjectName("checkinCode")
        self.horizontalLayout_10.addWidget(self.checkinCode)
        self.btnCheckin = QtWidgets.QPushButton(parent=self.checkinGroup)
        self.btnCheckin.setStyleSheet("background-color: #3b82f6; color: white; padding: 10px; font-size: 14px;")
        self.btnCheckin.setObjectName("btnCheckin")
        self.horizontalLayout_10.addWidget(self.btnCheckin)
        self.btnScanQR = QtWidgets.QPushButton(parent=self.checkinGroup)
        self.btnScanQR.setStyleSheet("background-color: #2563eb; color: white; padding: 10px; font-size: 14px;")
        self.btnScanQR.setObjectName("btnScanQR")
        self.horizontalLayout_10.addWidget(self.btnScanQR)
        self.verticalLayout_5.addWidget(self.checkinGroup)
        self.label_7 = QtWidgets.QLabel(parent=self.checkinTab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.checkinTable = QtWidgets.QTableWidget(parent=self.checkinTab)
        self.checkinTable.setStyleSheet("background-color: white;")
        self.checkinTable.setObjectName("checkinTable")
        self.checkinTable.setColumnCount(5)
        self.checkinTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.checkinTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkinTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkinTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkinTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkinTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout_5.addWidget(self.checkinTable)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnRefreshCheckin = QtWidgets.QPushButton(parent=self.checkinTab)
        self.btnRefreshCheckin.setStyleSheet("background-color: #94a3b8; color: white;")
        self.btnRefreshCheckin.setObjectName("btnRefreshCheckin")
        self.horizontalLayout_11.addWidget(self.btnRefreshCheckin)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_checkin_export = QtWidgets.QHBoxLayout()
        self.horizontalLayout_checkin_export.setObjectName("horizontalLayout_checkin_export")
        self.btnExportCheckin = QtWidgets.QPushButton(parent=self.checkinTab)
        self.btnExportCheckin.setStyleSheet("background-color: #94a3b8; color: white; padding: 6px 12px;")
        self.btnExportCheckin.setObjectName("btnExportCheckin")
        self.horizontalLayout_checkin_export.addWidget(self.btnExportCheckin)
        spacerCheckinExport = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_checkin_export.addItem(spacerCheckinExport)
        self.verticalLayout_5.addLayout(self.horizontalLayout_checkin_export)
        self.tabWidget.addTab(self.checkinTab, "")
        self.userMgmtTab = QtWidgets.QWidget()
        self.userMgmtTab.setObjectName("userMgmtTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.userMgmtTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnAddUser = QtWidgets.QPushButton(parent=self.userMgmtTab)
        self.btnAddUser.setStyleSheet("padding: 10px; font-size: 13px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: #3b82f6;")
        self.btnAddUser.setObjectName("btnAddUser")
        self.horizontalLayout_12.addWidget(self.btnAddUser)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.userTable = QtWidgets.QTableWidget(parent=self.userMgmtTab)
        self.userTable.setStyleSheet("background-color: white;")
        self.userTable.setObjectName("userTable")
        self.userTable.setColumnCount(5)
        self.userTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.userTable)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnEditUser = QtWidgets.QPushButton(parent=self.userMgmtTab)
        self.btnEditUser.setStyleSheet("background-color: #2563eb;\n"
"color: rgb(255, 255, 255);")
        self.btnEditUser.setObjectName("btnEditUser")
        self.horizontalLayout_13.addWidget(self.btnEditUser)
        self.btnDeleteUser = QtWidgets.QPushButton(parent=self.userMgmtTab)
        self.btnDeleteUser.setStyleSheet("background-color: #ef4444; color: white;")
        self.btnDeleteUser.setObjectName("btnDeleteUser")
        self.horizontalLayout_13.addWidget(self.btnDeleteUser)
        self.btnResetUserPwd = QtWidgets.QPushButton(parent=self.userMgmtTab)
        self.btnResetUserPwd.setStyleSheet("background-color: #3b82f6;\n"
"color: rgb(255, 255, 255);")
        self.btnResetUserPwd.setObjectName("btnResetUserPwd")
        self.horizontalLayout_13.addWidget(self.btnResetUserPwd)
        self.btnRefreshUser = QtWidgets.QPushButton(parent=self.userMgmtTab)
        self.btnRefreshUser.setStyleSheet("background-color: #94a3b8; color: white;")
        self.btnRefreshUser.setObjectName("btnRefreshUser")
        self.horizontalLayout_13.addWidget(self.btnRefreshUser)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.userMgmtTab, "")

        # ── Statistics Tab ──────────────────────────────────────────────────────
        self.statisticsTab = QtWidgets.QWidget()
        self.statisticsTab.setObjectName("statisticsTab")
        self.statisticsTab.setStyleSheet("background-color: #f0f0f0;")

        self.verticalLayout_stats = QtWidgets.QVBoxLayout(self.statisticsTab)
        self.verticalLayout_stats.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_stats.setSpacing(8)

        # ── Row 1: Event selector ────────────────────────────────────────────
        self.horizontalLayout_stats_top = QtWidgets.QHBoxLayout()

        self.lblStatsEvent = QtWidgets.QLabel(parent=self.statisticsTab)
        self.lblStatsEvent.setText("Event:")
        self.lblStatsEvent.setStyleSheet("color:#3b82f6; font-weight:bold; font-size:13px;")
        self.lblStatsEvent.setObjectName("lblStatsEvent")
        self.horizontalLayout_stats_top.addWidget(self.lblStatsEvent)

        self.statsEventCombo = QtWidgets.QComboBox(parent=self.statisticsTab)
        self.statsEventCombo.setMinimumWidth(260)
        self.statsEventCombo.setStyleSheet("""
            QComboBox {
                border: 1px solid #bdc3c7;
                border-radius: 4px;
                padding: 4px 8px;
                color: #1e293b;
                background: white;
                font-size: 13px;
            }
            QComboBox::drop-down { border: none; }
        """)
        self.statsEventCombo.setObjectName("statsEventCombo")
        self.horizontalLayout_stats_top.addWidget(self.statsEventCombo)

        spacerStatsTop = QtWidgets.QSpacerItem(40, 20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_stats_top.addItem(spacerStatsTop)

        self.verticalLayout_stats.addLayout(self.horizontalLayout_stats_top)

        # ── Row 2: Chart type toggle buttons ────────────────────────────────
        ACTIVE_STYLE = """
            QPushButton {
                background-color: #1e293b;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 7px 20px;
                font-size: 13px;
                font-weight: bold;
            }
            QPushButton:hover { background-color: #0f172a; }
        """
        INACTIVE_STYLE = """
            QPushButton {
                background-color: #e2e8f0;
                color: #64748b;
                border: none;
                border-radius: 4px;
                padding: 7px 20px;
                font-size: 13px;
            }
            QPushButton:hover { background-color: #cccccc; color: #1e293b; }
        """

        self.horizontalLayout_stats_btns = QtWidgets.QHBoxLayout()
        self.horizontalLayout_stats_btns.setSpacing(4)

        self.btnStatsBar = QtWidgets.QPushButton("Bar Chart", parent=self.statisticsTab)
        self.btnStatsBar.setObjectName("btnStatsBar")
        self.btnStatsBar.setStyleSheet(ACTIVE_STYLE)
        self.btnStatsBar.setProperty("active_style",  ACTIVE_STYLE)
        self.btnStatsBar.setProperty("inactive_style", INACTIVE_STYLE)
        self.horizontalLayout_stats_btns.addWidget(self.btnStatsBar)

        self.btnStatsLine = QtWidgets.QPushButton("Line Chart", parent=self.statisticsTab)
        self.btnStatsLine.setObjectName("btnStatsLine")
        self.btnStatsLine.setStyleSheet(INACTIVE_STYLE)
        self.btnStatsLine.setProperty("active_style",  ACTIVE_STYLE)
        self.btnStatsLine.setProperty("inactive_style", INACTIVE_STYLE)
        self.horizontalLayout_stats_btns.addWidget(self.btnStatsLine)

        self.btnStatsPie = QtWidgets.QPushButton("Pie Chart", parent=self.statisticsTab)
        self.btnStatsPie.setObjectName("btnStatsPie")
        self.btnStatsPie.setStyleSheet(INACTIVE_STYLE)
        self.btnStatsPie.setProperty("active_style",  ACTIVE_STYLE)
        self.btnStatsPie.setProperty("inactive_style", INACTIVE_STYLE)
        self.horizontalLayout_stats_btns.addWidget(self.btnStatsPie)

        spacerStatsBtns = QtWidgets.QSpacerItem(40, 20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_stats_btns.addItem(spacerStatsBtns)

        self.verticalLayout_stats.addLayout(self.horizontalLayout_stats_btns)

        # ── Chart area (không có GroupBox title, không có toolbar) ──────────
        self.statsChartGroup = QtWidgets.QFrame(parent=self.statisticsTab)
        self.statsChartGroup.setObjectName("statsChartGroup")
        self.statsChartGroup.setStyleSheet("""
            QFrame {
                background-color: white;
                border: 1px solid #f1f5f9;
                border-radius: 6px;
            }
        """)
        self.verticalLayoutStatsPlot = QtWidgets.QVBoxLayout(self.statsChartGroup)
        self.verticalLayoutStatsPlot.setContentsMargins(4, 4, 4, 4)
        self.verticalLayoutStatsPlot.setObjectName("verticalLayoutStatsPlot")
        self.verticalLayout_stats.addWidget(self.statsChartGroup)

        self.tabWidget.addTab(self.statisticsTab, "")
        self.contentLayout.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.contentWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Event Check-in Management System"))
        self.titleLabel.setText(_translate("MainWindow", "🎫  EVENT CHECK-IN MANAGEMENT SYSTEM"))
        self.lblRoleBadge.setText(_translate("MainWindow", "STAFF"))
        self.lblLoginUser.setText(_translate("MainWindow", "👤  Staff"))
        self.btnChangePassword.setText(_translate("MainWindow", "🔐 Change Password"))
        self.btnLogout.setText(_translate("MainWindow", "🚪 Logout"))
        self.labelEventSearch.setText(_translate("MainWindow", "🔍 Search:"))
        self.eventSearch.setPlaceholderText(_translate("MainWindow", "Enter event name, location..."))
        self.btnAddEvent.setText(_translate("MainWindow", "➕ Add New Event"))
        item = self.eventTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.eventTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Event Name"))
        item = self.eventTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.eventTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time"))
        item = self.eventTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Venue"))
        item = self.eventTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Description"))
        self.btnViewEvent.setText(_translate("MainWindow", "👁 View Details"))
        self.btnEditEvent.setText(_translate("MainWindow", "✏ Update"))
        self.btnDeleteEvent.setText(_translate("MainWindow", "🗑 Delete"))
        self.btnRefreshEvent.setText(_translate("MainWindow", "🔄 Refresh"))
        self.btnExportEvent.setText(_translate("MainWindow", "📥 Export CSV"))
        self.btnPrevEvent.setText(_translate("MainWindow", "◀ Prev"))
        self.btnNextEvent.setText(_translate("MainWindow", "Next ▶"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dashboardTab), _translate("MainWindow", "🏠 Dashboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.eventTab), _translate("MainWindow", "📅 Events"))
        self.label.setText(_translate("MainWindow", "🔍 Search:"))
        self.attendeeSearch.setPlaceholderText(_translate("MainWindow", "Enter name, email, phone number or organization..."))
        self.btnAddAttendee.setText(_translate("MainWindow", "➕ Add Attendee"))
        self.btnImportAttendee.setText(_translate("MainWindow", "📂 Import Excel/CSV"))
        item = self.attendeeTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.attendeeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.attendeeTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.attendeeTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.attendeeTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Organization"))
        item = self.attendeeTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Position"))
        self.btnEditAttendee.setText(_translate("MainWindow", "✏ Update"))
        self.btnDeleteAttendee.setText(_translate("MainWindow", "🗑 Delete"))
        self.btnHistoryAttendee.setText(_translate("MainWindow", "📜 History"))
        self.btnRefreshAttendee.setText(_translate("MainWindow", "🔄 Refresh"))
        self.btnExportAttendee.setText(_translate("MainWindow", "📥 Export CSV"))
        self.btnPrevAttendee.setText(_translate("MainWindow", "◀ Prev"))
        self.btnNextAttendee.setText(_translate("MainWindow", "Next ▶"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.attendeeTab), _translate("MainWindow", "👥 Attendees"))
        self.label_2.setText(_translate("MainWindow", "Select Event:"))
        self.btnRegisterAttendee.setText(_translate("MainWindow", "➕ Register Attendee"))
        item = self.registrationTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Check-in Code"))
        item = self.registrationTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.registrationTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.registrationTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Organization"))
        item = self.registrationTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Reg. Date"))
        item = self.registrationTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        self.btnGenerateQR.setText(_translate("MainWindow", "📱 Generate QR Code"))
        self.btnCancelRegistration.setText(_translate("MainWindow", "❌ Cancel Registration"))
        self.btnRefreshRegistration.setText(_translate("MainWindow", "🔄 Refresh"))
        self.btnExportRegistration.setText(_translate("MainWindow", "📥 Export CSV"))
        self.btnPrevRegistration.setText(_translate("MainWindow", "◀ Prev"))
        self.btnNextRegistration.setText(_translate("MainWindow", "Next ▶"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.registrationTab), _translate("MainWindow", "📋 Registrations"))
        self.label_3.setText(_translate("MainWindow", "Select Event:"))
        self.statsGroup.setTitle(_translate("MainWindow", "📊 Check-in Statistics"))
        self.label_4.setText(_translate("MainWindow", "Total Registered:"))
        self.totalRegisteredLabel.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Checked In:"))
        self.totalCheckedinLabel.setText(_translate("MainWindow", "0"))
        self.checkinGroup.setTitle(_translate("MainWindow", "✅ Perform Check-in"))
        self.label_6.setText(_translate("MainWindow", "Registration Code / QR:"))
        self.checkinCode.setPlaceholderText(_translate("MainWindow", "Enter registration code or scan QR..."))
        self.btnCheckin.setText(_translate("MainWindow", "✓ Check-in"))
        self.btnScanQR.setText(_translate("MainWindow", "📷 Scan QR"))
        self.label_7.setText(_translate("MainWindow", "📋 Checked-in List (this event):"))
        item = self.checkinTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.checkinTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.checkinTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Organization"))
        item = self.checkinTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Check-in Time"))
        item = self.checkinTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Reg. Code"))
        self.btnRefreshCheckin.setText(_translate("MainWindow", "🔄 Refresh"))
        self.btnExportCheckin.setText(_translate("MainWindow", "📥 Export CSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.checkinTab), _translate("MainWindow", "✅ Check-in"))
        self.btnAddUser.setText(_translate("MainWindow", "➕ Add Staff"))
        item = self.userTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.userTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.userTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Username"))
        item = self.userTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.userTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Role"))
        self.btnEditUser.setText(_translate("MainWindow", "✏ Update"))
        self.btnDeleteUser.setText(_translate("MainWindow", "🗑 Delete"))
        self.btnResetUserPwd.setText(_translate("MainWindow", "🔑 Reset Password"))
        self.btnRefreshUser.setText(_translate("MainWindow", "🔄 Refresh"))
        self.btnStatsBar.setText(_translate("MainWindow", "📊 Bar Chart"))
        self.btnStatsLine.setText(_translate("MainWindow", "📈 Line Chart"))
        self.btnStatsPie.setText(_translate("MainWindow", "🥧 Pie Chart"))
        self.lblStatsEvent.setText(_translate("MainWindow", "Select Event:"))
        # statsChartGroup is QFrame, no title needed
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.userMgmtTab), _translate("MainWindow", "👤 Staff Accounts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statisticsTab), _translate("MainWindow", "📊 Statistics"))