# Form implementation generated from reading ui file 'QRScannerDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QRScannerDialog(object):
    def setupUi(self, QRScannerDialog):
        QRScannerDialog.setObjectName("QRScannerDialog")
        QRScannerDialog.resize(720, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(QRScannerDialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=QRScannerDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: rgb(59, 230, 190); margin-bottom: 6px;")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.lblInstruction = QtWidgets.QLabel(parent=QRScannerDialog)
        self.lblInstruction.setStyleSheet("color: rgb(251, 7, 33); font-size: 12px;")
        self.lblInstruction.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblInstruction.setObjectName("lblInstruction")
        self.verticalLayout.addWidget(self.lblInstruction)
        self.horizontalLayout_video = QtWidgets.QHBoxLayout()
        self.horizontalLayout_video.setObjectName("horizontalLayout_video")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_video.addItem(spacerItem)
        self.videoLabel = QtWidgets.QLabel(parent=QRScannerDialog)
        self.videoLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.videoLabel.setMaximumSize(QtCore.QSize(640, 480))
        self.videoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")
        self.horizontalLayout_video.addWidget(self.videoLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_video.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_video)
        self.lblStatus = QtWidgets.QLabel(parent=QRScannerDialog)
        self.lblStatus.setText("")
        self.lblStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnClose = QtWidgets.QPushButton(parent=QRScannerDialog)
        self.btnClose.setMinimumSize(QtCore.QSize(0, 40))
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(QRScannerDialog)
        self.btnClose.clicked.connect(QRScannerDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(QRScannerDialog)

    def retranslateUi(self, QRScannerDialog):
        _translate = QtCore.QCoreApplication.translate
        QRScannerDialog.setWindowTitle(_translate("QRScannerDialog", "Scan QR Code"))
        self.lblTitle.setText(_translate("QRScannerDialog", "📷  Scan QR Code for Check-in"))
        self.lblInstruction.setText(_translate("QRScannerDialog", "Hold the QR code in front of the camera for automatic check-in"))
        self.videoLabel.setStyleSheet(_translate("QRScannerDialog", "border: 2px solid #34495e; border-radius: 8px; background-color: #1e293b;"))
        self.videoLabel.setText(_translate("QRScannerDialog", "📷 Starting camera..."))
        self.lblStatus.setStyleSheet(_translate("QRScannerDialog", "color: #16a34a; font-size: 13px; font-weight: bold; padding: 8px; background: #f0fdf4; border-radius: 6px;"))
        self.btnClose.setStyleSheet(_translate("QRScannerDialog", "QPushButton { background: #ef4444; color: white; border-radius: 6px; font-size: 13px; font-weight: bold; padding: 0 20px; } QPushButton:hover { background: #dc2626; }"))
        self.btnClose.setText(_translate("QRScannerDialog", "Close"))
