# Form implementation generated from reading ui file 'D:\HK2_2025_2026\KTLT_K25411E\Event_Check_in_Management\ui\RegistrationDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegistrationDialog(object):
    def setupUi(self, RegistrationDialog):
        RegistrationDialog.setObjectName("RegistrationDialog")
        RegistrationDialog.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(RegistrationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=RegistrationDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.attendeeCombo = QtWidgets.QComboBox(parent=RegistrationDialog)
        self.attendeeCombo.setObjectName("attendeeCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.attendeeCombo)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnRegister = QtWidgets.QPushButton(parent=RegistrationDialog)
        self.btnRegister.setStyleSheet("padding: 8px 15px;")
        self.btnRegister.setObjectName("btnRegister")
        self.horizontalLayout.addWidget(self.btnRegister)
        self.btnCancel = QtWidgets.QPushButton(parent=RegistrationDialog)
        self.btnCancel.setStyleSheet("padding: 8px 15px;")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(RegistrationDialog)
        self.btnCancel.clicked.connect(RegistrationDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RegistrationDialog)

    def retranslateUi(self, RegistrationDialog):
        _translate = QtCore.QCoreApplication.translate
        RegistrationDialog.setWindowTitle(_translate("RegistrationDialog", "Register Attendee"))
        self.label.setText(_translate("RegistrationDialog", "Select Attendee:"))
        self.btnRegister.setText(_translate("RegistrationDialog", "💾 Register"))
        self.btnCancel.setText(_translate("RegistrationDialog", "❌ Cancel"))
