# Form implementation generated from reading ui file 'D:\HK2_2025_2026\KTLT_K25411E\Event_Check_in_Management\ui\UserDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserDialog(object):
    def setupUi(self, UserDialog):
        UserDialog.setObjectName("UserDialog")
        UserDialog.resize(440, 420)
        UserDialog.setMinimumSize(QtCore.QSize(440, 420))
        UserDialog.setMaximumSize(QtCore.QSize(440, 420))
        self.verticalLayout = QtWidgets.QVBoxLayout(UserDialog)
        self.verticalLayout.setContentsMargins(28, 24, 28, 24)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=UserDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color:#2c3e50; margin-bottom:6px;")
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.lblFullName = QtWidgets.QLabel(parent=UserDialog)
        self.lblFullName.setStyleSheet("font-weight:bold; font-size:12px;")
        self.lblFullName.setObjectName("lblFullName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFullName)
        self.lineEditFullName = QtWidgets.QLineEdit(parent=UserDialog)
        self.lineEditFullName.setMinimumSize(QtCore.QSize(0, 34))
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditFullName)
        self.lblUsername = QtWidgets.QLabel(parent=UserDialog)
        self.lblUsername.setStyleSheet("font-weight:bold; font-size:12px;")
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblUsername)
        self.lineEditUsername = QtWidgets.QLineEdit(parent=UserDialog)
        self.lineEditUsername.setMinimumSize(QtCore.QSize(0, 34))
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditUsername)
        self.lblEmail = QtWidgets.QLabel(parent=UserDialog)
        self.lblEmail.setStyleSheet("font-weight:bold; font-size:12px;")
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblEmail)
        self.lineEditEmail = QtWidgets.QLineEdit(parent=UserDialog)
        self.lineEditEmail.setMinimumSize(QtCore.QSize(0, 34))
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditEmail)
        self.lblPassword = QtWidgets.QLabel(parent=UserDialog)
        self.lblPassword.setStyleSheet("font-weight:bold; font-size:12px;")
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=UserDialog)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(0, 34))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPassword)
        self.lblRole = QtWidgets.QLabel(parent=UserDialog)
        self.lblRole.setStyleSheet("font-weight:bold; font-size:12px;")
        self.lblRole.setObjectName("lblRole")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblRole)
        self.comboRole = QtWidgets.QComboBox(parent=UserDialog)
        self.comboRole.setMinimumSize(QtCore.QSize(0, 34))
        self.comboRole.setObjectName("comboRole")
        self.comboRole.addItem("")
        self.comboRole.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboRole)
        self.lblSecQuestion = QtWidgets.QLabel(parent=UserDialog)
        self.lblSecQuestion.setStyleSheet("font-weight:bold; font-size:12px;")
        self.lblSecQuestion.setObjectName("lblSecQuestion")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblSecQuestion)
        self.lineEditSecQuestion = QtWidgets.QLineEdit(parent=UserDialog)
        self.lineEditSecQuestion.setMinimumSize(QtCore.QSize(0, 34))
        self.lineEditSecQuestion.setObjectName("lineEditSecQuestion")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditSecQuestion)
        self.lblSecAnswer = QtWidgets.QLabel(parent=UserDialog)
        self.lblSecAnswer.setStyleSheet("font-weight:bold; font-size:12px;")
        self.lblSecAnswer.setObjectName("lblSecAnswer")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblSecAnswer)
        self.lineEditSecAnswer = QtWidgets.QLineEdit(parent=UserDialog)
        self.lineEditSecAnswer.setMinimumSize(QtCore.QSize(0, 34))
        self.lineEditSecAnswer.setObjectName("lineEditSecAnswer")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditSecAnswer)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(parent=UserDialog)
        self.btnSave.setMinimumSize(QtCore.QSize(0, 38))
        self.btnSave.setStyleSheet("QPushButton{\n"
"    background:#2ecc71;\n"
"    color:white;\n"
"    border-radius:6px;\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    padding:0 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:#27ae60;\n"
"}")
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(parent=UserDialog)
        self.btnCancel.setMinimumSize(QtCore.QSize(0, 38))
        self.btnCancel.setStyleSheet("QPushButton{\n"
"    background:#ecf0f1;\n"
"    color:#7f8c8d;\n"
"    border-radius:6px;\n"
"    font-size:13px;\n"
"    padding:0 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:#d5dbdb;\n"
"}")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(UserDialog)
        self.btnCancel.clicked.connect(UserDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserDialog)

    def retranslateUi(self, UserDialog):
        _translate = QtCore.QCoreApplication.translate
        UserDialog.setWindowTitle(_translate("UserDialog", "Add / Edit Account"))
        self.lblTitle.setText(_translate("UserDialog", "👤  Account Information"))
        self.lblFullName.setText(_translate("UserDialog", "Full Name:"))
        self.lineEditFullName.setPlaceholderText(_translate("UserDialog", "Enter full name..."))
        self.lblUsername.setText(_translate("UserDialog", "Username:"))
        self.lineEditUsername.setPlaceholderText(_translate("UserDialog", "Letters, numbers, underscores only..."))
        self.lblEmail.setText(_translate("UserDialog", "Email:"))
        self.lineEditEmail.setPlaceholderText(_translate("UserDialog", "example@email.com"))
        self.lblPassword.setText(_translate("UserDialog", "Password:"))
        self.lineEditPassword.setPlaceholderText(_translate("UserDialog", "Minimum 6 characters (leave blank to keep current when editing)..."))
        self.lblRole.setText(_translate("UserDialog", "Role:"))
        self.comboRole.setItemText(0, _translate("UserDialog", "👤  User"))
        self.comboRole.setItemText(1, _translate("UserDialog", "🔑  Admin"))
        self.lblSecQuestion.setText(_translate("UserDialog", "Security Question:"))
        self.lineEditSecQuestion.setPlaceholderText(_translate("UserDialog", "Security question for password recovery..."))
        self.lblSecAnswer.setText(_translate("UserDialog", "Answer:"))
        self.lineEditSecAnswer.setPlaceholderText(_translate("UserDialog", "Answer (case-insensitive)..."))
        self.btnSave.setText(_translate("UserDialog", "💾 Save"))
        self.btnCancel.setText(_translate("UserDialog", "Cancel"))
